name:                haskell-learn
version:             0.1.0.0
github:              "githubuser/haskell-learn"
license:             BSD-3-Clause
author:              "ArthurJordao"
maintainer:          "hi@arthurjordao.dev"
copyright:           "2023 Arthur Jordão"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ArthurJordao/haskell-learn#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- process
- time
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings
  - ScopedTypeVariables
  - NoFieldSelectors
  - DuplicateRecordFields

library:
  source-dirs: src

executables:
  haskell-learn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-learn

tests:
  haskell-learn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-learn
